### ISSUE TITLE
等边三角形

### ISSUE THREAD

**Issue by Sunny-117** [Sunny-117/js-challenges#224]

**Comment by veneno-o** [comment]
```html
<div id="app"></div>
```
```css
#app{
    width: 0;
    height: 0;
    border: 100px solid transparent;
    border-bottom-color: red;
}
```
```js
document.querySelector("#app").style.borderBottomWidth = 100 * Math.tan(Math.PI / 3) + "px";
```
